"use client";
import { useMemo, useState } from "react";
import "./globals.css";
import { Assistant } from "next/font/google";
import {
  ICartTotal,
  IProducts,
  IProductsToAdd,
} from "@/shared/model/products.model";
import {
  CartContext,
  CartTotalContext,
  SearchTextContext,
} from "@/core/context";

const assistant = Assistant({ subsets: ["latin"] });

export const metadata = {
  title: "Amazon Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [cartItems, setCartItems] = useState<IProductsToAdd[]>([]);
  const [total, setTotal] = useState<ICartTotal | null>(null);

  const cartItemsState = useMemo(
    () => ({
      cartItems,
      setCartItems,
    }),
    [cartItems]
  );
  const cartItemsTotalState = useMemo(
    () => ({
      total,
      setTotal,
    }),
    [total]
  );

  return (
    <html lang="en">
      <body className={assistant.className}>
        <CartContext.Provider value={cartItemsState}>
          <CartTotalContext.Provider value={cartItemsTotalState}>
            {children}
          </CartTotalContext.Provider>
        </CartContext.Provider>
      </body>
    </html>
  );
}
